### ISSUE TITLE
python app.py issue

### ISSUE THREAD

**Issue by RohitSingh1226** [CalciferZh/minimal-hand#43]
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 13, in <module>
    from wrappers import ModelPipeline
  File "C:\Users\faker\OneDrive\Desktop\minimal-hand\wrappers.py", line 4, in 
<module>
    import tensorflow as tf
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this 
DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive

Windows 10 OS 
installed all the requirements.txt still some issue with running the file

**Comment by CalciferZh** [comment]
Sorry but I'm afraid I cannot help with environmental issues.

**Comment by RohitSingh1226** [comment]
Okay thanks for the quick response, I have solved the issue(Reinstalled tensorflow)

Is it possible for both the hands?

**Comment by CalciferZh** [comment]
No, it works only for a single left hand. If there are two hands in the image at the same time, the model is likely to fail; if there is only one right hand, you may consider of flipping the image.
